# **The Basics**

In [ ]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.itemsize

8

In [ ]:
a.size


15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [ ]:
type(b)

numpy.ndarray

# **Array Creation**

In [ ]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [ ]:
# a = np.array(1,2,3,4)  # WRONG way, array takes 1 to 2 positional arguments whereas you are giving here 4 arguments
a = np.array([1,2,3,4]) # RIGHT way

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
c = np.array([[1,2],[3,4]], dtype=np.complex128)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# arange is the analogous to the python built-in range, but returns an array

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.arange(0,2,0.3) # When we use arange with floating point arguments, it is genrally not possible to predict the number of elements obtained, due to the finite point precision, so we use linspace.

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
from numpy import pi
np.linspace(0,2,9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)


# **Printing Arrays**

In [33]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [35]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [37]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [40]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# **Basic Operations**

In [41]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [42]:
c = a - b
print(c)

[20 29 38 47]


In [43]:
b ** 2

array([0, 1, 4, 9])

In [44]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [45]:
a < 35

array([ True,  True, False, False])

In [46]:

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

A * B  # element wise product

array([[2, 0],
       [0, 4]])

In [47]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [48]:
A.dot(B) # another way for matrix product

array([[5, 4],
       [3, 4]])

In [51]:
# Inplace modification

rg = np.random.default_rng(1)
a = np.ones((2,3), dtype= np.int_)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [53]:
b += a
b

array([[6.51182162, 6.9504637 , 6.14415961],
       [6.94864945, 6.31183145, 6.42332645]])

In [54]:
# some unary operation implemented as methods of the ndarray class, by default these operations apply to the array as though it were a list of numbers,regardless of its shape.
a.sum()

np.int64(18)

In [55]:
a.min()

np.int64(3)

In [56]:
a.max()

np.int64(3)

In [57]:
# Operations along the specified axis

b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
b.sum(axis=0) # Sum of each column

array([12, 15, 18, 21])

In [59]:
b.min(axis=1) # min of each row

array([0, 4, 8])

In [60]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# **Universal Functions**

In [61]:
B = np.arange(3)
B

array([0, 1, 2])

In [62]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [63]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [64]:
C = np.array([2.,-1,4.])
np.add(B,C)

array([2., 0., 6.])